# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-expenditure

# >> macros
# << macros

Summary:    Expenditure
Version:    0.3
Release:    1
Group:      Qt/Qt
License:    GPL-3.0-only
URL:        https://github.com/yajo10/harbour-imgorganizer
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-expenditure.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils

%description
App for tracking expenses between friends - it's for SailfishOS

%if 0%{?_chum}
Title: Expenditure
Type: desktop-application
DeveloperName: yajo
Categories:
 - Office
Custom:
  Repo: https://github.com/yajo10/harbour-expenditure
PackageIcon: https://github.com/yajo10/harbour-expenditure/raw/master/icons/172x172/harbour-expenditure.png
Screenshots:
 - https://github.com/yajo10/harbour-imgorganizer/raw/master/screenshots/Screenshot1.jpg
 - https://github.com/yajo10/harbour-imgorganizer/raw/master/screenshots/Screenshot2.jpg
 - https://github.com/yajo10/harbour-imgorganizer/raw/master/screenshots/Screenshot3.jpg
 - https://github.com/yajo10/harbour-imgorganizer/raw/master/screenshots/Screenshot4.jpg
Links:
  Homepage: https://github.com/yajo10/harbour-expenditure
  Help: https://github.com/yajo10/harbour-expenditure/issues
  Bugtracker: https://github.com/yajo10/harbour-expenditure/issues
  Donation: https://liberapay.com/yajo10/donate
%endif


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
